/***************************************************************************
* TNG033, Fö 7                                                             *
* Defines a class Flight                                                   *
* header file flight.h                                                     *
* **************************************************************************/

//Read sec. 7.1, 7.2, 7.3.1-7.3.4, 7.4 of course book

#ifndef FLIGHT_H_INCLUDED
#define FLIGHT_H_INCLUDED

#include <iostream>

#include "clock.h"

using namespace std;


class Flight
{
  public:

    //constructors
    Flight() = delete; //no default constructor is generated by the compiler

    Flight(int n);

    Flight(int n, int dh, int dm, int ah, int am);

   friend ostream& operator<< (ostream& os, const Flight& f);

  private:
   int number;  //flight's number

   Clock dep;   //flight's departure time
   Clock arr;   //flight's arrival time
};



#endif // FLIGHT_H_INCLUDED
